### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by Steviegt6** [proudmuslim-dev/proudmuslim-dev#2]
I don't believe the MC server EULA at all applies to independent clients that operate standalone?

**Comment by Steviegt6** [comment]
Furthermore, the EULA doesn't forbid monetization; the EULA forbids monetization directly off of the software produced by Mojang. Badlion and Lunar are mods for the game, and people donate and support the code used in mods, not Minecraft itself. This is different to servers as most server content utilizes solely in-game mechanics and features.

**Comment by proudmuslim-dev** [comment]
My personal github repository is NOT the place for this. My contact info is clearly placed on my profile, and please contact me directly in the future @Steviegt6
