### ISSUE TITLE
Lunar Client on the AUR

### ISSUE THREAD

**Issue by pollen00** [proudmuslim-dev/proudmuslim-dev#3]
So I saw you took down Lunar and BLC on the AUR, as a Lunar client user this is incredibly inconvenient and unneeded. I'm posting here since this was the only way I found to contact you.

Your reasoning in the deletion request was "Violation of the minecraft EULA", but then you posted a link to the SERVER EULA!
https://lists.archlinux.org/pipermail/aur-requests/2021-May/053971.html

Not only is it unneeded to get it removed EVEN IF IT WAS VIOLATING EULA, your deletion request wasn't even correct. You went out of your way to delete something that wasn't even breaking the rules.

**Comment by pollen00** [comment]
Looking at some of your other stuff, it seems like you have a thing against other clients (trashing Laby with no evidence), which is hilarious since it just looks like you want to take down anything not Forge. Any client (including forge) has plenty of issues and I agree that alternatives should be provided, but please refrain from unrightfully taking down things from the AUR.

**Comment by Steviegt6** [comment]
In my issue (see: #2), I also touch on the lack of validity in the claims regardless of whether these clients would be considered servers or not. They are monetizing their own programming, not content in Minecraft itself.
